// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/luique16/quitocoin/ent/block"
	"github.com/luique16/quitocoin/internal/domain/transaction"
)

// BlockCreate is the builder for creating a Block entity.
type BlockCreate struct {
	config
	mutation *BlockMutation
	hooks    []Hook
}

// SetHash sets the "hash" field.
func (bc *BlockCreate) SetHash(s string) *BlockCreate {
	bc.mutation.SetHash(s)
	return bc
}

// SetIndex sets the "index" field.
func (bc *BlockCreate) SetIndex(i int) *BlockCreate {
	bc.mutation.SetIndex(i)
	return bc
}

// SetPreviousHash sets the "previous_hash" field.
func (bc *BlockCreate) SetPreviousHash(s string) *BlockCreate {
	bc.mutation.SetPreviousHash(s)
	return bc
}

// SetNonce sets the "nonce" field.
func (bc *BlockCreate) SetNonce(i int64) *BlockCreate {
	bc.mutation.SetNonce(i)
	return bc
}

// SetMiner sets the "miner" field.
func (bc *BlockCreate) SetMiner(s string) *BlockCreate {
	bc.mutation.SetMiner(s)
	return bc
}

// SetReward sets the "reward" field.
func (bc *BlockCreate) SetReward(f float64) *BlockCreate {
	bc.mutation.SetReward(f)
	return bc
}

// SetTransactions sets the "transactions" field.
func (bc *BlockCreate) SetTransactions(t []transaction.Transaction) *BlockCreate {
	bc.mutation.SetTransactions(t)
	return bc
}

// SetCreatedAt sets the "created_at" field.
func (bc *BlockCreate) SetCreatedAt(t time.Time) *BlockCreate {
	bc.mutation.SetCreatedAt(t)
	return bc
}

// Mutation returns the BlockMutation object of the builder.
func (bc *BlockCreate) Mutation() *BlockMutation {
	return bc.mutation
}

// Save creates the Block in the database.
func (bc *BlockCreate) Save(ctx context.Context) (*Block, error) {
	return withHooks(ctx, bc.sqlSave, bc.mutation, bc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (bc *BlockCreate) SaveX(ctx context.Context) *Block {
	v, err := bc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bc *BlockCreate) Exec(ctx context.Context) error {
	_, err := bc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bc *BlockCreate) ExecX(ctx context.Context) {
	if err := bc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bc *BlockCreate) check() error {
	if _, ok := bc.mutation.Hash(); !ok {
		return &ValidationError{Name: "hash", err: errors.New(`ent: missing required field "Block.hash"`)}
	}
	if _, ok := bc.mutation.Index(); !ok {
		return &ValidationError{Name: "index", err: errors.New(`ent: missing required field "Block.index"`)}
	}
	if _, ok := bc.mutation.PreviousHash(); !ok {
		return &ValidationError{Name: "previous_hash", err: errors.New(`ent: missing required field "Block.previous_hash"`)}
	}
	if _, ok := bc.mutation.Nonce(); !ok {
		return &ValidationError{Name: "nonce", err: errors.New(`ent: missing required field "Block.nonce"`)}
	}
	if _, ok := bc.mutation.Miner(); !ok {
		return &ValidationError{Name: "miner", err: errors.New(`ent: missing required field "Block.miner"`)}
	}
	if _, ok := bc.mutation.Reward(); !ok {
		return &ValidationError{Name: "reward", err: errors.New(`ent: missing required field "Block.reward"`)}
	}
	if _, ok := bc.mutation.Transactions(); !ok {
		return &ValidationError{Name: "transactions", err: errors.New(`ent: missing required field "Block.transactions"`)}
	}
	if _, ok := bc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Block.created_at"`)}
	}
	return nil
}

func (bc *BlockCreate) sqlSave(ctx context.Context) (*Block, error) {
	if err := bc.check(); err != nil {
		return nil, err
	}
	_node, _spec := bc.createSpec()
	if err := sqlgraph.CreateNode(ctx, bc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	bc.mutation.id = &_node.ID
	bc.mutation.done = true
	return _node, nil
}

func (bc *BlockCreate) createSpec() (*Block, *sqlgraph.CreateSpec) {
	var (
		_node = &Block{config: bc.config}
		_spec = sqlgraph.NewCreateSpec(block.Table, sqlgraph.NewFieldSpec(block.FieldID, field.TypeInt))
	)
	if value, ok := bc.mutation.Hash(); ok {
		_spec.SetField(block.FieldHash, field.TypeString, value)
		_node.Hash = value
	}
	if value, ok := bc.mutation.Index(); ok {
		_spec.SetField(block.FieldIndex, field.TypeInt, value)
		_node.Index = value
	}
	if value, ok := bc.mutation.PreviousHash(); ok {
		_spec.SetField(block.FieldPreviousHash, field.TypeString, value)
		_node.PreviousHash = value
	}
	if value, ok := bc.mutation.Nonce(); ok {
		_spec.SetField(block.FieldNonce, field.TypeInt64, value)
		_node.Nonce = value
	}
	if value, ok := bc.mutation.Miner(); ok {
		_spec.SetField(block.FieldMiner, field.TypeString, value)
		_node.Miner = value
	}
	if value, ok := bc.mutation.Reward(); ok {
		_spec.SetField(block.FieldReward, field.TypeFloat64, value)
		_node.Reward = value
	}
	if value, ok := bc.mutation.Transactions(); ok {
		_spec.SetField(block.FieldTransactions, field.TypeJSON, value)
		_node.Transactions = value
	}
	if value, ok := bc.mutation.CreatedAt(); ok {
		_spec.SetField(block.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// BlockCreateBulk is the builder for creating many Block entities in bulk.
type BlockCreateBulk struct {
	config
	err      error
	builders []*BlockCreate
}

// Save creates the Block entities in the database.
func (bcb *BlockCreateBulk) Save(ctx context.Context) ([]*Block, error) {
	if bcb.err != nil {
		return nil, bcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(bcb.builders))
	nodes := make([]*Block, len(bcb.builders))
	mutators := make([]Mutator, len(bcb.builders))
	for i := range bcb.builders {
		func(i int, root context.Context) {
			builder := bcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BlockMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, bcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, bcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, bcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (bcb *BlockCreateBulk) SaveX(ctx context.Context) []*Block {
	v, err := bcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bcb *BlockCreateBulk) Exec(ctx context.Context) error {
	_, err := bcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bcb *BlockCreateBulk) ExecX(ctx context.Context) {
	if err := bcb.Exec(ctx); err != nil {
		panic(err)
	}
}
