// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/luique16/quitocoin/ent/block"
	"github.com/luique16/quitocoin/internal/domain/transaction"
)

// Block is the model entity for the Block schema.
type Block struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Hash holds the value of the "hash" field.
	Hash string `json:"hash,omitempty"`
	// Index holds the value of the "index" field.
	Index int `json:"index,omitempty"`
	// PreviousHash holds the value of the "previous_hash" field.
	PreviousHash string `json:"previous_hash,omitempty"`
	// Nonce holds the value of the "nonce" field.
	Nonce int64 `json:"nonce,omitempty"`
	// Miner holds the value of the "miner" field.
	Miner string `json:"miner,omitempty"`
	// Reward holds the value of the "reward" field.
	Reward float64 `json:"reward,omitempty"`
	// Transactions holds the value of the "transactions" field.
	Transactions []transaction.Transaction `json:"transactions,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Block) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case block.FieldTransactions:
			values[i] = new([]byte)
		case block.FieldReward:
			values[i] = new(sql.NullFloat64)
		case block.FieldID, block.FieldIndex, block.FieldNonce:
			values[i] = new(sql.NullInt64)
		case block.FieldHash, block.FieldPreviousHash, block.FieldMiner:
			values[i] = new(sql.NullString)
		case block.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Block fields.
func (b *Block) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case block.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			b.ID = int(value.Int64)
		case block.FieldHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field hash", values[i])
			} else if value.Valid {
				b.Hash = value.String
			}
		case block.FieldIndex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field index", values[i])
			} else if value.Valid {
				b.Index = int(value.Int64)
			}
		case block.FieldPreviousHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field previous_hash", values[i])
			} else if value.Valid {
				b.PreviousHash = value.String
			}
		case block.FieldNonce:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field nonce", values[i])
			} else if value.Valid {
				b.Nonce = value.Int64
			}
		case block.FieldMiner:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field miner", values[i])
			} else if value.Valid {
				b.Miner = value.String
			}
		case block.FieldReward:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field reward", values[i])
			} else if value.Valid {
				b.Reward = value.Float64
			}
		case block.FieldTransactions:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field transactions", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &b.Transactions); err != nil {
					return fmt.Errorf("unmarshal field transactions: %w", err)
				}
			}
		case block.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				b.CreatedAt = value.Time
			}
		default:
			b.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Block.
// This includes values selected through modifiers, order, etc.
func (b *Block) Value(name string) (ent.Value, error) {
	return b.selectValues.Get(name)
}

// Update returns a builder for updating this Block.
// Note that you need to call Block.Unwrap() before calling this method if this Block
// was returned from a transaction, and the transaction was committed or rolled back.
func (b *Block) Update() *BlockUpdateOne {
	return NewBlockClient(b.config).UpdateOne(b)
}

// Unwrap unwraps the Block entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (b *Block) Unwrap() *Block {
	_tx, ok := b.config.driver.(*txDriver)
	if !ok {
		panic("ent: Block is not a transactional entity")
	}
	b.config.driver = _tx.drv
	return b
}

// String implements the fmt.Stringer.
func (b *Block) String() string {
	var builder strings.Builder
	builder.WriteString("Block(")
	builder.WriteString(fmt.Sprintf("id=%v, ", b.ID))
	builder.WriteString("hash=")
	builder.WriteString(b.Hash)
	builder.WriteString(", ")
	builder.WriteString("index=")
	builder.WriteString(fmt.Sprintf("%v", b.Index))
	builder.WriteString(", ")
	builder.WriteString("previous_hash=")
	builder.WriteString(b.PreviousHash)
	builder.WriteString(", ")
	builder.WriteString("nonce=")
	builder.WriteString(fmt.Sprintf("%v", b.Nonce))
	builder.WriteString(", ")
	builder.WriteString("miner=")
	builder.WriteString(b.Miner)
	builder.WriteString(", ")
	builder.WriteString("reward=")
	builder.WriteString(fmt.Sprintf("%v", b.Reward))
	builder.WriteString(", ")
	builder.WriteString("transactions=")
	builder.WriteString(fmt.Sprintf("%v", b.Transactions))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(b.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Blocks is a parsable slice of Block.
type Blocks []*Block
