// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/luique16/quitocoin/ent/block"
	"github.com/luique16/quitocoin/ent/predicate"
	"github.com/luique16/quitocoin/internal/domain/transaction"
)

// BlockUpdate is the builder for updating Block entities.
type BlockUpdate struct {
	config
	hooks    []Hook
	mutation *BlockMutation
}

// Where appends a list predicates to the BlockUpdate builder.
func (bu *BlockUpdate) Where(ps ...predicate.Block) *BlockUpdate {
	bu.mutation.Where(ps...)
	return bu
}

// SetIndex sets the "index" field.
func (bu *BlockUpdate) SetIndex(i int) *BlockUpdate {
	bu.mutation.ResetIndex()
	bu.mutation.SetIndex(i)
	return bu
}

// SetNillableIndex sets the "index" field if the given value is not nil.
func (bu *BlockUpdate) SetNillableIndex(i *int) *BlockUpdate {
	if i != nil {
		bu.SetIndex(*i)
	}
	return bu
}

// AddIndex adds i to the "index" field.
func (bu *BlockUpdate) AddIndex(i int) *BlockUpdate {
	bu.mutation.AddIndex(i)
	return bu
}

// SetPreviousHash sets the "previous_hash" field.
func (bu *BlockUpdate) SetPreviousHash(s string) *BlockUpdate {
	bu.mutation.SetPreviousHash(s)
	return bu
}

// SetNillablePreviousHash sets the "previous_hash" field if the given value is not nil.
func (bu *BlockUpdate) SetNillablePreviousHash(s *string) *BlockUpdate {
	if s != nil {
		bu.SetPreviousHash(*s)
	}
	return bu
}

// SetNonce sets the "nonce" field.
func (bu *BlockUpdate) SetNonce(i int64) *BlockUpdate {
	bu.mutation.ResetNonce()
	bu.mutation.SetNonce(i)
	return bu
}

// SetNillableNonce sets the "nonce" field if the given value is not nil.
func (bu *BlockUpdate) SetNillableNonce(i *int64) *BlockUpdate {
	if i != nil {
		bu.SetNonce(*i)
	}
	return bu
}

// AddNonce adds i to the "nonce" field.
func (bu *BlockUpdate) AddNonce(i int64) *BlockUpdate {
	bu.mutation.AddNonce(i)
	return bu
}

// SetMiner sets the "miner" field.
func (bu *BlockUpdate) SetMiner(s string) *BlockUpdate {
	bu.mutation.SetMiner(s)
	return bu
}

// SetNillableMiner sets the "miner" field if the given value is not nil.
func (bu *BlockUpdate) SetNillableMiner(s *string) *BlockUpdate {
	if s != nil {
		bu.SetMiner(*s)
	}
	return bu
}

// SetReward sets the "reward" field.
func (bu *BlockUpdate) SetReward(f float64) *BlockUpdate {
	bu.mutation.ResetReward()
	bu.mutation.SetReward(f)
	return bu
}

// SetNillableReward sets the "reward" field if the given value is not nil.
func (bu *BlockUpdate) SetNillableReward(f *float64) *BlockUpdate {
	if f != nil {
		bu.SetReward(*f)
	}
	return bu
}

// AddReward adds f to the "reward" field.
func (bu *BlockUpdate) AddReward(f float64) *BlockUpdate {
	bu.mutation.AddReward(f)
	return bu
}

// SetTransactions sets the "transactions" field.
func (bu *BlockUpdate) SetTransactions(t []transaction.Transaction) *BlockUpdate {
	bu.mutation.SetTransactions(t)
	return bu
}

// AppendTransactions appends t to the "transactions" field.
func (bu *BlockUpdate) AppendTransactions(t []transaction.Transaction) *BlockUpdate {
	bu.mutation.AppendTransactions(t)
	return bu
}

// SetCreatedAt sets the "created_at" field.
func (bu *BlockUpdate) SetCreatedAt(t time.Time) *BlockUpdate {
	bu.mutation.SetCreatedAt(t)
	return bu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (bu *BlockUpdate) SetNillableCreatedAt(t *time.Time) *BlockUpdate {
	if t != nil {
		bu.SetCreatedAt(*t)
	}
	return bu
}

// Mutation returns the BlockMutation object of the builder.
func (bu *BlockUpdate) Mutation() *BlockMutation {
	return bu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (bu *BlockUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, bu.sqlSave, bu.mutation, bu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (bu *BlockUpdate) SaveX(ctx context.Context) int {
	affected, err := bu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (bu *BlockUpdate) Exec(ctx context.Context) error {
	_, err := bu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bu *BlockUpdate) ExecX(ctx context.Context) {
	if err := bu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (bu *BlockUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(block.Table, block.Columns, sqlgraph.NewFieldSpec(block.FieldID, field.TypeInt))
	if ps := bu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := bu.mutation.Index(); ok {
		_spec.SetField(block.FieldIndex, field.TypeInt, value)
	}
	if value, ok := bu.mutation.AddedIndex(); ok {
		_spec.AddField(block.FieldIndex, field.TypeInt, value)
	}
	if value, ok := bu.mutation.PreviousHash(); ok {
		_spec.SetField(block.FieldPreviousHash, field.TypeString, value)
	}
	if value, ok := bu.mutation.Nonce(); ok {
		_spec.SetField(block.FieldNonce, field.TypeInt64, value)
	}
	if value, ok := bu.mutation.AddedNonce(); ok {
		_spec.AddField(block.FieldNonce, field.TypeInt64, value)
	}
	if value, ok := bu.mutation.Miner(); ok {
		_spec.SetField(block.FieldMiner, field.TypeString, value)
	}
	if value, ok := bu.mutation.Reward(); ok {
		_spec.SetField(block.FieldReward, field.TypeFloat64, value)
	}
	if value, ok := bu.mutation.AddedReward(); ok {
		_spec.AddField(block.FieldReward, field.TypeFloat64, value)
	}
	if value, ok := bu.mutation.Transactions(); ok {
		_spec.SetField(block.FieldTransactions, field.TypeJSON, value)
	}
	if value, ok := bu.mutation.AppendedTransactions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, block.FieldTransactions, value)
		})
	}
	if value, ok := bu.mutation.CreatedAt(); ok {
		_spec.SetField(block.FieldCreatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, bu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{block.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	bu.mutation.done = true
	return n, nil
}

// BlockUpdateOne is the builder for updating a single Block entity.
type BlockUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BlockMutation
}

// SetIndex sets the "index" field.
func (buo *BlockUpdateOne) SetIndex(i int) *BlockUpdateOne {
	buo.mutation.ResetIndex()
	buo.mutation.SetIndex(i)
	return buo
}

// SetNillableIndex sets the "index" field if the given value is not nil.
func (buo *BlockUpdateOne) SetNillableIndex(i *int) *BlockUpdateOne {
	if i != nil {
		buo.SetIndex(*i)
	}
	return buo
}

// AddIndex adds i to the "index" field.
func (buo *BlockUpdateOne) AddIndex(i int) *BlockUpdateOne {
	buo.mutation.AddIndex(i)
	return buo
}

// SetPreviousHash sets the "previous_hash" field.
func (buo *BlockUpdateOne) SetPreviousHash(s string) *BlockUpdateOne {
	buo.mutation.SetPreviousHash(s)
	return buo
}

// SetNillablePreviousHash sets the "previous_hash" field if the given value is not nil.
func (buo *BlockUpdateOne) SetNillablePreviousHash(s *string) *BlockUpdateOne {
	if s != nil {
		buo.SetPreviousHash(*s)
	}
	return buo
}

// SetNonce sets the "nonce" field.
func (buo *BlockUpdateOne) SetNonce(i int64) *BlockUpdateOne {
	buo.mutation.ResetNonce()
	buo.mutation.SetNonce(i)
	return buo
}

// SetNillableNonce sets the "nonce" field if the given value is not nil.
func (buo *BlockUpdateOne) SetNillableNonce(i *int64) *BlockUpdateOne {
	if i != nil {
		buo.SetNonce(*i)
	}
	return buo
}

// AddNonce adds i to the "nonce" field.
func (buo *BlockUpdateOne) AddNonce(i int64) *BlockUpdateOne {
	buo.mutation.AddNonce(i)
	return buo
}

// SetMiner sets the "miner" field.
func (buo *BlockUpdateOne) SetMiner(s string) *BlockUpdateOne {
	buo.mutation.SetMiner(s)
	return buo
}

// SetNillableMiner sets the "miner" field if the given value is not nil.
func (buo *BlockUpdateOne) SetNillableMiner(s *string) *BlockUpdateOne {
	if s != nil {
		buo.SetMiner(*s)
	}
	return buo
}

// SetReward sets the "reward" field.
func (buo *BlockUpdateOne) SetReward(f float64) *BlockUpdateOne {
	buo.mutation.ResetReward()
	buo.mutation.SetReward(f)
	return buo
}

// SetNillableReward sets the "reward" field if the given value is not nil.
func (buo *BlockUpdateOne) SetNillableReward(f *float64) *BlockUpdateOne {
	if f != nil {
		buo.SetReward(*f)
	}
	return buo
}

// AddReward adds f to the "reward" field.
func (buo *BlockUpdateOne) AddReward(f float64) *BlockUpdateOne {
	buo.mutation.AddReward(f)
	return buo
}

// SetTransactions sets the "transactions" field.
func (buo *BlockUpdateOne) SetTransactions(t []transaction.Transaction) *BlockUpdateOne {
	buo.mutation.SetTransactions(t)
	return buo
}

// AppendTransactions appends t to the "transactions" field.
func (buo *BlockUpdateOne) AppendTransactions(t []transaction.Transaction) *BlockUpdateOne {
	buo.mutation.AppendTransactions(t)
	return buo
}

// SetCreatedAt sets the "created_at" field.
func (buo *BlockUpdateOne) SetCreatedAt(t time.Time) *BlockUpdateOne {
	buo.mutation.SetCreatedAt(t)
	return buo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (buo *BlockUpdateOne) SetNillableCreatedAt(t *time.Time) *BlockUpdateOne {
	if t != nil {
		buo.SetCreatedAt(*t)
	}
	return buo
}

// Mutation returns the BlockMutation object of the builder.
func (buo *BlockUpdateOne) Mutation() *BlockMutation {
	return buo.mutation
}

// Where appends a list predicates to the BlockUpdate builder.
func (buo *BlockUpdateOne) Where(ps ...predicate.Block) *BlockUpdateOne {
	buo.mutation.Where(ps...)
	return buo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (buo *BlockUpdateOne) Select(field string, fields ...string) *BlockUpdateOne {
	buo.fields = append([]string{field}, fields...)
	return buo
}

// Save executes the query and returns the updated Block entity.
func (buo *BlockUpdateOne) Save(ctx context.Context) (*Block, error) {
	return withHooks(ctx, buo.sqlSave, buo.mutation, buo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (buo *BlockUpdateOne) SaveX(ctx context.Context) *Block {
	node, err := buo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (buo *BlockUpdateOne) Exec(ctx context.Context) error {
	_, err := buo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (buo *BlockUpdateOne) ExecX(ctx context.Context) {
	if err := buo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (buo *BlockUpdateOne) sqlSave(ctx context.Context) (_node *Block, err error) {
	_spec := sqlgraph.NewUpdateSpec(block.Table, block.Columns, sqlgraph.NewFieldSpec(block.FieldID, field.TypeInt))
	id, ok := buo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Block.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := buo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, block.FieldID)
		for _, f := range fields {
			if !block.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != block.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := buo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := buo.mutation.Index(); ok {
		_spec.SetField(block.FieldIndex, field.TypeInt, value)
	}
	if value, ok := buo.mutation.AddedIndex(); ok {
		_spec.AddField(block.FieldIndex, field.TypeInt, value)
	}
	if value, ok := buo.mutation.PreviousHash(); ok {
		_spec.SetField(block.FieldPreviousHash, field.TypeString, value)
	}
	if value, ok := buo.mutation.Nonce(); ok {
		_spec.SetField(block.FieldNonce, field.TypeInt64, value)
	}
	if value, ok := buo.mutation.AddedNonce(); ok {
		_spec.AddField(block.FieldNonce, field.TypeInt64, value)
	}
	if value, ok := buo.mutation.Miner(); ok {
		_spec.SetField(block.FieldMiner, field.TypeString, value)
	}
	if value, ok := buo.mutation.Reward(); ok {
		_spec.SetField(block.FieldReward, field.TypeFloat64, value)
	}
	if value, ok := buo.mutation.AddedReward(); ok {
		_spec.AddField(block.FieldReward, field.TypeFloat64, value)
	}
	if value, ok := buo.mutation.Transactions(); ok {
		_spec.SetField(block.FieldTransactions, field.TypeJSON, value)
	}
	if value, ok := buo.mutation.AppendedTransactions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, block.FieldTransactions, value)
		})
	}
	if value, ok := buo.mutation.CreatedAt(); ok {
		_spec.SetField(block.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &Block{config: buo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, buo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{block.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	buo.mutation.done = true
	return _node, nil
}
