// Code generated by ent, DO NOT EDIT.

package block

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the block type in the database.
	Label = "block"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldHash holds the string denoting the hash field in the database.
	FieldHash = "hash"
	// FieldIndex holds the string denoting the index field in the database.
	FieldIndex = "index"
	// FieldPreviousHash holds the string denoting the previous_hash field in the database.
	FieldPreviousHash = "previous_hash"
	// FieldNonce holds the string denoting the nonce field in the database.
	FieldNonce = "nonce"
	// FieldMiner holds the string denoting the miner field in the database.
	FieldMiner = "miner"
	// FieldReward holds the string denoting the reward field in the database.
	FieldReward = "reward"
	// FieldTransactions holds the string denoting the transactions field in the database.
	FieldTransactions = "transactions"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the block in the database.
	Table = "blocks"
)

// Columns holds all SQL columns for block fields.
var Columns = []string{
	FieldID,
	FieldHash,
	FieldIndex,
	FieldPreviousHash,
	FieldNonce,
	FieldMiner,
	FieldReward,
	FieldTransactions,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Block queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByHash orders the results by the hash field.
func ByHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHash, opts...).ToFunc()
}

// ByIndex orders the results by the index field.
func ByIndex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIndex, opts...).ToFunc()
}

// ByPreviousHash orders the results by the previous_hash field.
func ByPreviousHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPreviousHash, opts...).ToFunc()
}

// ByNonce orders the results by the nonce field.
func ByNonce(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNonce, opts...).ToFunc()
}

// ByMiner orders the results by the miner field.
func ByMiner(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMiner, opts...).ToFunc()
}

// ByReward orders the results by the reward field.
func ByReward(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReward, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
