// Code generated by ent, DO NOT EDIT.

package block

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/luique16/quitocoin/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Block {
	return predicate.Block(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Block {
	return predicate.Block(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Block {
	return predicate.Block(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Block {
	return predicate.Block(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Block {
	return predicate.Block(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Block {
	return predicate.Block(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Block {
	return predicate.Block(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Block {
	return predicate.Block(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Block {
	return predicate.Block(sql.FieldLTE(FieldID, id))
}

// Hash applies equality check predicate on the "hash" field. It's identical to HashEQ.
func Hash(v string) predicate.Block {
	return predicate.Block(sql.FieldEQ(FieldHash, v))
}

// Index applies equality check predicate on the "index" field. It's identical to IndexEQ.
func Index(v int) predicate.Block {
	return predicate.Block(sql.FieldEQ(FieldIndex, v))
}

// PreviousHash applies equality check predicate on the "previous_hash" field. It's identical to PreviousHashEQ.
func PreviousHash(v string) predicate.Block {
	return predicate.Block(sql.FieldEQ(FieldPreviousHash, v))
}

// Nonce applies equality check predicate on the "nonce" field. It's identical to NonceEQ.
func Nonce(v int64) predicate.Block {
	return predicate.Block(sql.FieldEQ(FieldNonce, v))
}

// Miner applies equality check predicate on the "miner" field. It's identical to MinerEQ.
func Miner(v string) predicate.Block {
	return predicate.Block(sql.FieldEQ(FieldMiner, v))
}

// Reward applies equality check predicate on the "reward" field. It's identical to RewardEQ.
func Reward(v float64) predicate.Block {
	return predicate.Block(sql.FieldEQ(FieldReward, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Block {
	return predicate.Block(sql.FieldEQ(FieldCreatedAt, v))
}

// HashEQ applies the EQ predicate on the "hash" field.
func HashEQ(v string) predicate.Block {
	return predicate.Block(sql.FieldEQ(FieldHash, v))
}

// HashNEQ applies the NEQ predicate on the "hash" field.
func HashNEQ(v string) predicate.Block {
	return predicate.Block(sql.FieldNEQ(FieldHash, v))
}

// HashIn applies the In predicate on the "hash" field.
func HashIn(vs ...string) predicate.Block {
	return predicate.Block(sql.FieldIn(FieldHash, vs...))
}

// HashNotIn applies the NotIn predicate on the "hash" field.
func HashNotIn(vs ...string) predicate.Block {
	return predicate.Block(sql.FieldNotIn(FieldHash, vs...))
}

// HashGT applies the GT predicate on the "hash" field.
func HashGT(v string) predicate.Block {
	return predicate.Block(sql.FieldGT(FieldHash, v))
}

// HashGTE applies the GTE predicate on the "hash" field.
func HashGTE(v string) predicate.Block {
	return predicate.Block(sql.FieldGTE(FieldHash, v))
}

// HashLT applies the LT predicate on the "hash" field.
func HashLT(v string) predicate.Block {
	return predicate.Block(sql.FieldLT(FieldHash, v))
}

// HashLTE applies the LTE predicate on the "hash" field.
func HashLTE(v string) predicate.Block {
	return predicate.Block(sql.FieldLTE(FieldHash, v))
}

// HashContains applies the Contains predicate on the "hash" field.
func HashContains(v string) predicate.Block {
	return predicate.Block(sql.FieldContains(FieldHash, v))
}

// HashHasPrefix applies the HasPrefix predicate on the "hash" field.
func HashHasPrefix(v string) predicate.Block {
	return predicate.Block(sql.FieldHasPrefix(FieldHash, v))
}

// HashHasSuffix applies the HasSuffix predicate on the "hash" field.
func HashHasSuffix(v string) predicate.Block {
	return predicate.Block(sql.FieldHasSuffix(FieldHash, v))
}

// HashEqualFold applies the EqualFold predicate on the "hash" field.
func HashEqualFold(v string) predicate.Block {
	return predicate.Block(sql.FieldEqualFold(FieldHash, v))
}

// HashContainsFold applies the ContainsFold predicate on the "hash" field.
func HashContainsFold(v string) predicate.Block {
	return predicate.Block(sql.FieldContainsFold(FieldHash, v))
}

// IndexEQ applies the EQ predicate on the "index" field.
func IndexEQ(v int) predicate.Block {
	return predicate.Block(sql.FieldEQ(FieldIndex, v))
}

// IndexNEQ applies the NEQ predicate on the "index" field.
func IndexNEQ(v int) predicate.Block {
	return predicate.Block(sql.FieldNEQ(FieldIndex, v))
}

// IndexIn applies the In predicate on the "index" field.
func IndexIn(vs ...int) predicate.Block {
	return predicate.Block(sql.FieldIn(FieldIndex, vs...))
}

// IndexNotIn applies the NotIn predicate on the "index" field.
func IndexNotIn(vs ...int) predicate.Block {
	return predicate.Block(sql.FieldNotIn(FieldIndex, vs...))
}

// IndexGT applies the GT predicate on the "index" field.
func IndexGT(v int) predicate.Block {
	return predicate.Block(sql.FieldGT(FieldIndex, v))
}

// IndexGTE applies the GTE predicate on the "index" field.
func IndexGTE(v int) predicate.Block {
	return predicate.Block(sql.FieldGTE(FieldIndex, v))
}

// IndexLT applies the LT predicate on the "index" field.
func IndexLT(v int) predicate.Block {
	return predicate.Block(sql.FieldLT(FieldIndex, v))
}

// IndexLTE applies the LTE predicate on the "index" field.
func IndexLTE(v int) predicate.Block {
	return predicate.Block(sql.FieldLTE(FieldIndex, v))
}

// PreviousHashEQ applies the EQ predicate on the "previous_hash" field.
func PreviousHashEQ(v string) predicate.Block {
	return predicate.Block(sql.FieldEQ(FieldPreviousHash, v))
}

// PreviousHashNEQ applies the NEQ predicate on the "previous_hash" field.
func PreviousHashNEQ(v string) predicate.Block {
	return predicate.Block(sql.FieldNEQ(FieldPreviousHash, v))
}

// PreviousHashIn applies the In predicate on the "previous_hash" field.
func PreviousHashIn(vs ...string) predicate.Block {
	return predicate.Block(sql.FieldIn(FieldPreviousHash, vs...))
}

// PreviousHashNotIn applies the NotIn predicate on the "previous_hash" field.
func PreviousHashNotIn(vs ...string) predicate.Block {
	return predicate.Block(sql.FieldNotIn(FieldPreviousHash, vs...))
}

// PreviousHashGT applies the GT predicate on the "previous_hash" field.
func PreviousHashGT(v string) predicate.Block {
	return predicate.Block(sql.FieldGT(FieldPreviousHash, v))
}

// PreviousHashGTE applies the GTE predicate on the "previous_hash" field.
func PreviousHashGTE(v string) predicate.Block {
	return predicate.Block(sql.FieldGTE(FieldPreviousHash, v))
}

// PreviousHashLT applies the LT predicate on the "previous_hash" field.
func PreviousHashLT(v string) predicate.Block {
	return predicate.Block(sql.FieldLT(FieldPreviousHash, v))
}

// PreviousHashLTE applies the LTE predicate on the "previous_hash" field.
func PreviousHashLTE(v string) predicate.Block {
	return predicate.Block(sql.FieldLTE(FieldPreviousHash, v))
}

// PreviousHashContains applies the Contains predicate on the "previous_hash" field.
func PreviousHashContains(v string) predicate.Block {
	return predicate.Block(sql.FieldContains(FieldPreviousHash, v))
}

// PreviousHashHasPrefix applies the HasPrefix predicate on the "previous_hash" field.
func PreviousHashHasPrefix(v string) predicate.Block {
	return predicate.Block(sql.FieldHasPrefix(FieldPreviousHash, v))
}

// PreviousHashHasSuffix applies the HasSuffix predicate on the "previous_hash" field.
func PreviousHashHasSuffix(v string) predicate.Block {
	return predicate.Block(sql.FieldHasSuffix(FieldPreviousHash, v))
}

// PreviousHashEqualFold applies the EqualFold predicate on the "previous_hash" field.
func PreviousHashEqualFold(v string) predicate.Block {
	return predicate.Block(sql.FieldEqualFold(FieldPreviousHash, v))
}

// PreviousHashContainsFold applies the ContainsFold predicate on the "previous_hash" field.
func PreviousHashContainsFold(v string) predicate.Block {
	return predicate.Block(sql.FieldContainsFold(FieldPreviousHash, v))
}

// NonceEQ applies the EQ predicate on the "nonce" field.
func NonceEQ(v int64) predicate.Block {
	return predicate.Block(sql.FieldEQ(FieldNonce, v))
}

// NonceNEQ applies the NEQ predicate on the "nonce" field.
func NonceNEQ(v int64) predicate.Block {
	return predicate.Block(sql.FieldNEQ(FieldNonce, v))
}

// NonceIn applies the In predicate on the "nonce" field.
func NonceIn(vs ...int64) predicate.Block {
	return predicate.Block(sql.FieldIn(FieldNonce, vs...))
}

// NonceNotIn applies the NotIn predicate on the "nonce" field.
func NonceNotIn(vs ...int64) predicate.Block {
	return predicate.Block(sql.FieldNotIn(FieldNonce, vs...))
}

// NonceGT applies the GT predicate on the "nonce" field.
func NonceGT(v int64) predicate.Block {
	return predicate.Block(sql.FieldGT(FieldNonce, v))
}

// NonceGTE applies the GTE predicate on the "nonce" field.
func NonceGTE(v int64) predicate.Block {
	return predicate.Block(sql.FieldGTE(FieldNonce, v))
}

// NonceLT applies the LT predicate on the "nonce" field.
func NonceLT(v int64) predicate.Block {
	return predicate.Block(sql.FieldLT(FieldNonce, v))
}

// NonceLTE applies the LTE predicate on the "nonce" field.
func NonceLTE(v int64) predicate.Block {
	return predicate.Block(sql.FieldLTE(FieldNonce, v))
}

// MinerEQ applies the EQ predicate on the "miner" field.
func MinerEQ(v string) predicate.Block {
	return predicate.Block(sql.FieldEQ(FieldMiner, v))
}

// MinerNEQ applies the NEQ predicate on the "miner" field.
func MinerNEQ(v string) predicate.Block {
	return predicate.Block(sql.FieldNEQ(FieldMiner, v))
}

// MinerIn applies the In predicate on the "miner" field.
func MinerIn(vs ...string) predicate.Block {
	return predicate.Block(sql.FieldIn(FieldMiner, vs...))
}

// MinerNotIn applies the NotIn predicate on the "miner" field.
func MinerNotIn(vs ...string) predicate.Block {
	return predicate.Block(sql.FieldNotIn(FieldMiner, vs...))
}

// MinerGT applies the GT predicate on the "miner" field.
func MinerGT(v string) predicate.Block {
	return predicate.Block(sql.FieldGT(FieldMiner, v))
}

// MinerGTE applies the GTE predicate on the "miner" field.
func MinerGTE(v string) predicate.Block {
	return predicate.Block(sql.FieldGTE(FieldMiner, v))
}

// MinerLT applies the LT predicate on the "miner" field.
func MinerLT(v string) predicate.Block {
	return predicate.Block(sql.FieldLT(FieldMiner, v))
}

// MinerLTE applies the LTE predicate on the "miner" field.
func MinerLTE(v string) predicate.Block {
	return predicate.Block(sql.FieldLTE(FieldMiner, v))
}

// MinerContains applies the Contains predicate on the "miner" field.
func MinerContains(v string) predicate.Block {
	return predicate.Block(sql.FieldContains(FieldMiner, v))
}

// MinerHasPrefix applies the HasPrefix predicate on the "miner" field.
func MinerHasPrefix(v string) predicate.Block {
	return predicate.Block(sql.FieldHasPrefix(FieldMiner, v))
}

// MinerHasSuffix applies the HasSuffix predicate on the "miner" field.
func MinerHasSuffix(v string) predicate.Block {
	return predicate.Block(sql.FieldHasSuffix(FieldMiner, v))
}

// MinerEqualFold applies the EqualFold predicate on the "miner" field.
func MinerEqualFold(v string) predicate.Block {
	return predicate.Block(sql.FieldEqualFold(FieldMiner, v))
}

// MinerContainsFold applies the ContainsFold predicate on the "miner" field.
func MinerContainsFold(v string) predicate.Block {
	return predicate.Block(sql.FieldContainsFold(FieldMiner, v))
}

// RewardEQ applies the EQ predicate on the "reward" field.
func RewardEQ(v float64) predicate.Block {
	return predicate.Block(sql.FieldEQ(FieldReward, v))
}

// RewardNEQ applies the NEQ predicate on the "reward" field.
func RewardNEQ(v float64) predicate.Block {
	return predicate.Block(sql.FieldNEQ(FieldReward, v))
}

// RewardIn applies the In predicate on the "reward" field.
func RewardIn(vs ...float64) predicate.Block {
	return predicate.Block(sql.FieldIn(FieldReward, vs...))
}

// RewardNotIn applies the NotIn predicate on the "reward" field.
func RewardNotIn(vs ...float64) predicate.Block {
	return predicate.Block(sql.FieldNotIn(FieldReward, vs...))
}

// RewardGT applies the GT predicate on the "reward" field.
func RewardGT(v float64) predicate.Block {
	return predicate.Block(sql.FieldGT(FieldReward, v))
}

// RewardGTE applies the GTE predicate on the "reward" field.
func RewardGTE(v float64) predicate.Block {
	return predicate.Block(sql.FieldGTE(FieldReward, v))
}

// RewardLT applies the LT predicate on the "reward" field.
func RewardLT(v float64) predicate.Block {
	return predicate.Block(sql.FieldLT(FieldReward, v))
}

// RewardLTE applies the LTE predicate on the "reward" field.
func RewardLTE(v float64) predicate.Block {
	return predicate.Block(sql.FieldLTE(FieldReward, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Block {
	return predicate.Block(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Block {
	return predicate.Block(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Block {
	return predicate.Block(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Block {
	return predicate.Block(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Block {
	return predicate.Block(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Block {
	return predicate.Block(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Block {
	return predicate.Block(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Block {
	return predicate.Block(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Block) predicate.Block {
	return predicate.Block(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Block) predicate.Block {
	return predicate.Block(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Block) predicate.Block {
	return predicate.Block(sql.NotPredicates(p))
}
