// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Block is the predicate function for block builders.
type Block func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
